<?php
require __DIR__.'/app/core.php';
if (!logged_in()) { header('Location: '.url('login')); exit; }
function go(string $s): void { header('Location: ?section='.$s); exit; }
function head_admin(): void { ?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="<?=url('assets/style.css')?>"><title>Админ-панель</title></head><body><div class="admin"><aside><h2><?=e(setting('site_name'))?></h2><a href="<?=url()?>">Открыть сайт</a><a href="?section=dashboard">Обзор</a><a href="?section=content&type=page">Страницы</a><a href="?section=content&type=post">Посты</a><a href="?section=content&type=product">Товары</a><a href="?section=categories">Категории</a><a href="?section=menus">Меню</a><a href="?section=buttons">Кнопки</a><a href="?section=comments">Комментарии</a><a href="?section=orders">Заказы</a><?php if(is_admin()):?><a href="?section=users">Пользователи</a><a href="?section=settings">Настройки</a><?php endif;?><a href="<?=url('logout')?>">Выйти</a></aside><main><?php if($f=flash()):?><p class="notice"><?=e($f)?></p><?php endif;?>
<?php }
function foot_admin(): void { ?></main></div><script src="<?=url('assets/editor.js')?>?v=20260928-4"></script></body></html><?php }

if ($_SERVER['REQUEST_METHOD']==='POST') {
 verify_csrf(); $a=$_POST['action']??'';
 if($a==='save' && can_edit()){
  $id=(int)$_POST['id'];$type=$_POST['type'];$slug=slugify($_POST['slug']?:$_POST['title']);
  $v=[$_POST['status'],$_POST['title'],$slug,$_POST['body'],$_POST['excerpt'],$_POST['image'],$_POST['template'],$_POST['language'],$_POST['translation_group']?:bin2hex(random_bytes(12)),(int)$_POST['category_id']?:null,$_POST['seo_title'],$_POST['seo_description'],isset($_POST['review_enabled'])?1:0,$_POST['review_text'],isset($_POST['comments_enabled'])?1:0,now()];
  if($id){$v[]=$id;db()->prepare('UPDATE content SET status=?,title=?,slug=?,body=?,excerpt=?,image=?,template=?,language=?,translation_group=?,category_id=?,seo_title=?,seo_description=?,review_enabled=?,review_text=?,comments_enabled=?,updated_at=? WHERE id=?')->execute($v);}
  else{array_splice($v,10,0,[user()['id']]);db()->prepare('INSERT INTO content(status,title,slug,body,excerpt,image,template,language,translation_group,category_id,author_id,seo_title,seo_description,review_enabled,review_text,comments_enabled,updated_at,type,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute(array_merge($v,[$type,now()]));}
  flash('Сохранено.');go('content&type='.$type);
 }
 if($a==='category' && can_edit()){db()->prepare('INSERT INTO categories(name,slug,description) VALUES(?,?,?)')->execute([$_POST['name'],slugify($_POST['slug']?:$_POST['name']),$_POST['description']]);flash('Категория создана.');go('categories');}
 if($a==='menu' && can_edit()){db()->prepare('INSERT INTO menus(name,location) VALUES(?,?)')->execute([$_POST['name'],$_POST['location']]);flash('Меню создано.');go('menus');}
 if($a==='menu_item' && can_edit()){db()->prepare('INSERT INTO menu_items(menu_id,label,url,sort_order) VALUES(?,?,?,?)')->execute([(int)$_POST['menu_id'],$_POST['label'],$_POST['url'],(int)$_POST['sort_order']]);flash('Пункт добавлен.');go('menus');}
 if($a==='button' && can_edit()){db()->prepare('INSERT INTO site_buttons(name,label,url,placement) VALUES(?,?,?,?)')->execute([$_POST['name'],$_POST['label'],$_POST['url'],$_POST['placement']]);flash('Кнопка добавлена.');go('buttons');}
 if($a==='settings' && is_admin()){foreach(['site_name','logo','footer_text','default_language','languages','blog_excerpt_length'] as $k)save_setting($k,$_POST[$k]??'');flash('Настройки сохранены.');go('settings');}
 if($a==='user' && is_admin()){db()->prepare('INSERT INTO users(name,email,password,role,created_at) VALUES(?,?,?,?,?)')->execute([$_POST['name'],$_POST['email'],password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['role'],now()]);flash('Пользователь создан.');go('users');}
}
$section=$_GET['section']??'dashboard'; head_admin();
if($section==='dashboard'){
 $n=[];foreach(['page','post','product'] as $t){$q=db()->prepare('SELECT COUNT(*) FROM content WHERE type=?');$q->execute([$t]);$n[$t]=$q->fetchColumn();}
 ?><h1>Панель управления</h1><div class="stats"><div>Страниц<b><?=$n['page']?></b></div><div>Постов<b><?=$n['post']?></b></div><div>Товаров<b><?=$n['product']?></b></div></div><p><a class="button" href="?section=edit&type=page">Новая страница</a> <a class="button" href="?section=edit&type=post">Новый пост</a></p><?php
} elseif($section==='content'){
 $type=in_array($_GET['type']??'', ['page','post','product'],true)?$_GET['type']:'page';$q=db()->prepare('SELECT id,title,slug,status,language FROM content WHERE type=? ORDER BY updated_at DESC');$q->execute([$type]);
 ?><h1><?=e(['page'=>'Страницы','post'=>'Посты','product'=>'Товары'][$type])?></h1><p><a class="button" href="?section=edit&type=<?=$type?>">Создать</a></p><table><tr><th>Название</th><th>Адрес</th><th>Статус</th><th>Язык</th><th></th></tr><?php foreach($q as $x):?><tr><td><?=e($x['title'])?></td><td><?=e($x['slug'])?></td><td><?=e($x['status'])?></td><td><?=e($x['language'])?></td><td><a href="?section=edit&id=<?=$x['id']?>">Изменить</a></td></tr><?php endforeach;?></table><?php
} elseif($section==='edit' && can_edit()){
 $id=(int)($_GET['id']??0);$type=$_GET['type']??'page';$x=['id'=>0,'status'=>'draft','title'=>'','slug'=>'','body'=>'','excerpt'=>'','image'=>'','template'=>'default','language'=>setting('default_language','ru'),'translation_group'=>'','category_id'=>'','seo_title'=>'','seo_description'=>'','review_enabled'=>0,'review_text'=>'','comments_enabled'=>1];if($id){$q=db()->prepare('SELECT * FROM content WHERE id=?');$q->execute([$id]);$x=$q->fetch(PDO::FETCH_ASSOC);$type=$x['type'];}$cats=db()->query('SELECT * FROM categories')->fetchAll(PDO::FETCH_ASSOC);
 ?><h1><?=$id?'Редактирование':'Новый материал'?></h1><form method="post" class="editor"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=$x['id']?>"><input type="hidden" name="type" value="<?=e($type)?>"><label>Название<input name="title" value="<?=e($x['title'])?>" required></label><label>Адрес (slug)<input name="slug" value="<?=e($x['slug'])?>"></label><label>Статус<select name="status"><option value="draft">Черновик</option><option value="published" <?=$x['status']==='published'?'selected':''?>>Опубликован</option></select></label><label>Язык<select name="language"><?php foreach(languages() as $code=>$name):?><option value="<?=$code?>" <?=$x['language']===$code?'selected':''?>><?=e($name)?></option><?php endforeach;?></select></label><label>Группа переводов<input name="translation_group" value="<?=e($x['translation_group'])?>"></label><?php if($type==='post'):?><label>Категория<select name="category_id"><option value="">Без категории</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$x['category_id']==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></label><?php endif;?><label>URL изображения<input name="image" value="<?=e($x['image'])?>"></label><label>Анонс<input name="excerpt" value="<?=e($x['excerpt'])?>"></label><label>Макет<select name="template"><option value="default">Обычный</option><option value="wide">Широкий</option><option value="landing">Лендинг</option></select></label><label>Содержание<textarea class="rich" name="body"><?=e($x['body'])?></textarea></label><fieldset><legend>SEO</legend><input name="seo_title" placeholder="SEO title" value="<?=e($x['seo_title'])?>"><textarea name="seo_description" placeholder="SEO description"><?=e($x['seo_description'])?></textarea></fieldset><label><input type="checkbox" name="comments_enabled" <?=$x['comments_enabled']?'checked':''?>> Комментарии</label><label><input type="checkbox" name="review_enabled" <?=$x['review_enabled']?'checked':''?>> Мнение автора</label><textarea name="review_text"><?=e($x['review_text'])?></textarea><button>Сохранить</button></form><?php
} elseif($section==='categories' && can_edit()){
 ?><h1>Категории</h1><form method="post" class="card inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="category"><input name="name" placeholder="Название" required><input name="slug" placeholder="Адрес"><input name="description" placeholder="Описание"><button>Добавить</button></form><?php foreach(db()->query('SELECT * FROM categories') as $c):?><p><?=e($c['name'])?> — <?=e($c['slug'])?></p><?php endforeach;?><?php
} elseif($section==='menus' && can_edit()){
 $menus=db()->query('SELECT * FROM menus')->fetchAll(PDO::FETCH_ASSOC);?><h1>Меню</h1><form method="post" class="card inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="menu"><input name="name" placeholder="Название" required><select name="location"><option value="header">Header</option><option value="footer">Footer</option></select><button>Создать</button></form><?php foreach($menus as $m):?><form method="post" class="card inline-form"><b><?=e($m['name'])?></b><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="menu_item"><input type="hidden" name="menu_id" value="<?=$m['id']?>"><input name="label" placeholder="Текст" required><input name="url" placeholder="Ссылка" required><input name="sort_order" type="number" value="0"><button>Добавить пункт</button></form><?php endforeach;?><?php
} elseif($section==='buttons' && can_edit()){
 ?><h1>Кнопки</h1><form method="post" class="card inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="button"><input name="name" placeholder="Имя" required><input name="label" placeholder="Текст" required><input name="url" placeholder="Ссылка" required><select name="placement"><option value="header">Header</option><option value="footer">Footer</option></select><button>Добавить</button></form><?php
} elseif($section==='settings' && is_admin()){
 ?><h1>Настройки</h1><form method="post" class="editor"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><label>Название<input name="site_name" value="<?=e(setting('site_name'))?>"></label><label>Логотип URL<input name="logo" value="<?=e(setting('logo'))?>"></label><label>Footer<input name="footer_text" value="<?=e(setting('footer_text'))?>"></label><label>Длина анонса<input name="blog_excerpt_length" value="<?=e(setting('blog_excerpt_length'))?>"></label><label>Язык<input name="default_language" value="<?=e(setting('default_language'))?>"></label><textarea name="languages"><?=e(setting('languages'))?></textarea><button>Сохранить</button></form><?php
} elseif($section==='users' && is_admin()){
 ?><h1>Пользователи</h1><form method="post" class="card inline-form"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="user"><input name="name" placeholder="Имя" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Пароль" required><select name="role"><option value="user">Пользователь</option><option value="editor">Редактор</option><option value="admin">Администратор</option></select><button>Создать</button></form><?php
} else { echo '<h1>Раздел недоступен</h1>'; }
foot_admin();
