<?php
if (!file_exists(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require __DIR__.'/app/core.php';
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
$base=trim(parse_url(config()['base_url'],PHP_URL_PATH)??'','/'); if($base&&str_starts_with($path,$base))$path=trim(substr($path,strlen($base)),'/');

/* robots.txt и sitemap.xml — обязательны для индексации и проверки сайта в Google Ads */
if($path==='robots.txt'){ header('Content-Type: text/plain; charset=utf-8'); $host=($_SERVER['HTTPS']??'')==='on'?'https':'http'; echo "User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /login\nSitemap: {$host}{$_SERVER['HTTP_HOST']}".url('sitemap.xml')."\n"; exit; }
if($path==='sitemap.xml'){ header('Content-Type: application/xml; charset=utf-8'); echo '<?xml version="1.0" encoding="UTF-8"?>'."\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n"; $urls=[['loc'=>url(),'lastmod'=>now()]]; foreach(db()->query('SELECT slug,updated_at,language,type FROM content WHERE status="published" ORDER BY id') as $r){ $p=$r['type']==='page'?url($r['slug']):url($r['type'].'/'.$r['slug']); $urls[]=['loc'=>$p,'lastmod'=>substr((string)$r['updated_at'],0,10)]; } foreach(array_unique(array_map(fn($u)=>$u['loc'],$urls)) as $u){ $lu=array_values(array_filter($urls,fn($x)=>$x['loc']===$u))[0]; echo "  <url><loc>".e($lu['loc'])."</loc><lastmod>".e($lu['lastmod'])."</lastmod></url>\n"; } echo "</urlset>"; exit; }

if($path==='admin'){ require __DIR__.'/admin.php'; exit; }
if($path==='logout'){session_destroy();header('Location: '.url());exit;}
if($path==='login' && $_SERVER['REQUEST_METHOD']==='POST'){ $s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([$_POST['email']??'']);$u=$s->fetch(PDO::FETCH_ASSOC);if($u&&password_verify($_POST['password']??'',$u['password'])){$_SESSION['user']=['id'=>$u['id'],'name'=>$u['name'],'role'=>$u['role']];header('Location: '.url('admin'));exit;} flash('Неверный email или пароль.');}
if($path==='login'){render_header('Вход');?><h1>Вход</h1><form method="post" class="card"><label>Email<input name="email" type="email" required></label><label>Пароль<input name="password" type="password" required></label><button>Войти</button></form><?php render_footer();exit;}
if($path==='comment' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
 if(trim($_POST['body']??'')===''||trim($_POST['name']??'')===''){flash('Заполните имя и текст комментария.');}
 else{db()->prepare('INSERT INTO comments(content_id,name,email,body,created_at) VALUES(?,?,?,?,?)')->execute([(int)$_POST['content_id'],$_POST['name'],$_POST['email'],$_POST['body'],now()]);flash('Комментарий отправлен на модерацию.');}
 header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
if($path==='order' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
 $okName=trim($_POST['name']??'')!==''; $okContact=trim($_POST['phone']??'')!==''||filter_var($_POST['email']??'',FILTER_VALIDATE_EMAIL); $okConsent=!consent_required()||!empty($_POST['consent']);
 if(!$okName||!$okContact){flash('Заполните имя и телефон или email для связи.');}
 elseif(!$okConsent){flash('Необходимо согласие на обработку персональных данных.');}
 else{db()->prepare('INSERT INTO orders(kind,product_id,customer_name,email,phone,message,created_at) VALUES(?,?,?,?,?,?,?)')->execute([$_POST['kind'],(int)($_POST['product_id']??0)?:null,$_POST['name'],$_POST['email'],$_POST['phone'],$_POST['message'],now()]);sf_do_action('order_created',(int)db()->lastInsertId());flash('Заявка принята. Мы свяжемся с вами.');}
 header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
$language=lang();
$homeId=(int)setting('home_page_id','0'); $blogId=(int)setting('blog_page_id','0');
if ($homeId && $path==='') { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page" AND status="published"');$q->execute([$homeId]);$homeSlug=(string)$q->fetchColumn();if($homeSlug!==''){header('Location: '.url($homeSlug),true,302);exit;} }
if ($blogId) { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page"');$q->execute([$blogId]);if($path!=='' && $path===(string)$q->fetchColumn()) $path='blog'; }
if($path==='blog'||str_starts_with($path,'category/')) { $cat=null;if(str_starts_with($path,'category/')){$s=db()->prepare('SELECT * FROM categories WHERE slug=?');$s->execute([substr($path,9)]);$cat=$s->fetch(PDO::FETCH_ASSOC);} $sql='SELECT c.*,u.name author,ca.name category FROM content c JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type="post" AND c.status="published" AND c.language=?';$args=[$language];if($cat){$sql.=' AND c.category_id=?';$args[]=$cat['id'];}$sql.=' ORDER BY c.created_at DESC';$s=db()->prepare($sql);$s->execute($args);$posts=$s->fetchAll(PDO::FETCH_ASSOC);render_header($cat?$cat['name']:'Блог');?><h1><?=e($cat['name']??'Блог')?></h1><div class="grid"><?php foreach($posts as $p):?><article class="card"><?php if($p['image']):?><img class="cover" src="<?=e($p['image'])?>" alt="<?=e($p['title'])?>"><?php endif;?><h2><a href="<?=url('post/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e(mb_strimwidth(strip_tags($p['excerpt']?:$p['body']),0,(int)setting('blog_excerpt_length','180'),'…'))?></p><small><?=e($p['category']??'')?> · <?=e($p['created_at'])?></small></article><?php endforeach;?></div><?php render_footer();exit; }
if($path==='shop'||$path==='services'){$s=db()->prepare('SELECT * FROM content WHERE type="product" AND status="published" AND language=? ORDER BY created_at DESC');$s->execute([$language]);$items=$s->fetchAll(PDO::FETCH_ASSOC);render_header(setting('services_title','Услуги'));?><h1><?=e(setting('services_title','Услуги'))?></h1><div class="grid"><?php foreach($items as $p):?><article class="card service-tile"><?php if($p['image']):?><img class="cover" src="<?=e($p['image'])?>" alt="<?=e($p['title'])?>"><?php endif;?><h2><a href="<?=url('product/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e($p['excerpt'])?></p><?php if($p['price']!==null):?><p class="price"><b><?=e(number_format((float)$p['price'],0,'',' '))?> <?=e($p['price_currency'])?></b></p><?php endif;?><a class="button" href="<?=url('product/'.$p['slug'])?>#order"><?=e($p['cta_label'] ?: 'Заказать')?></a></article><?php endforeach;?></div><?php render_footer();exit;}
$parts=explode('/',$path,2);$type=match($parts[0]??''){ 'post'=>'post','product'=>'product',default=>'page'};$slug=$type==='page'?($path?:'home'):($parts[1]??'');$s=db()->prepare('SELECT c.*,u.name author,ca.name category FROM content c JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type=? AND c.slug=? AND c.language=? AND c.status="published"');$s->execute([$type,$slug,$language]);$item=$s->fetch(PDO::FETCH_ASSOC);if(!$item){http_response_code(404);render_header('Страница не найдена');echo '<h1>Страница не найдена</h1><p>Воспользуйтесь меню или вернитесь на <a href="'.url().'">главную</a>.</p>';render_footer();exit;}
render_header($item['seo_title']?:$item['title']);?><article class="article <?='template-'.e($item['template'])?>"><?php if($item['image']):?><img class="hero" src="<?=e($item['image'])?>" alt="<?=e($item['title'])?>"><?php endif;?><h1><?=e($item['title'])?></h1><?php if($type==='post'):?><p class="meta"><?=e($item['author'])?> · <?=e($item['created_at'])?> <?php if($item['category']):?>· <a href="<?=url('category/'.slugify($item['category']))?>"><?=e($item['category'])?></a><?php endif;?></p><?php endif;?><div class="content"><?=sf_shortcodes_content(sf_apply_filters('the_content',$item['body'],$item))?></div><?php if($item['review_enabled']):?><aside class="review"><b>Мнение автора</b><p><?=nl2br(e($item['review_text']))?></p></aside><?php endif;?><?php if($type==='product'):?>
<section class="card order" id="order"><h2><?=e($item['cta_label'] ?: 'Оставить заявку')?></h2>
<?php if($item['price']!==null):?><p class="price">Стоимость: <b><?=e(number_format((float)$item['price'],0,'',' '))?> <?=e($item['price_currency'])?></b></p><?php endif;?>
<form method="post" action="<?=url('order')?>"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="kind" value="service"><input type="hidden" name="product_id" value="<?=$item['id']?>"><label>Имя<input name="name" required></label><label>Телефон<input name="phone" type="tel"></label><label>Email<input name="email" type="email"></label><label>Сообщение<textarea name="message"></textarea></label><?=consent_checkbox_html()?><p class="fineprint">Заполните телефон или email — хотя бы один способ связи обязателен.</p><button>Отправить заявку</button></form></section><?php endif;?><?php if($item['comments_enabled']):$q=db()->prepare('SELECT * FROM comments WHERE content_id=? AND status="approved" ORDER BY created_at');$q->execute([$item['id']]);?><section class="comments"><h2>Комментарии</h2><?php foreach($q as $c):?><div class="comment"><b><?=e($c['name'])?></b><p><?=nl2br(e($c['body']))?></p></div><?php endforeach;?><form method="post" action="<?=url('comment')?>" class="card"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="content_id" value="<?=$item['id']?>"><input name="name" placeholder="Имя" required><input name="email" type="email" placeholder="Email" required><textarea name="body" placeholder="Комментарий" required></textarea><button>Отправить</button></form></section><?php endif;?></article><?php render_footer(); ?>
