<?php
if (!file_exists(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require __DIR__.'/app/core.php';
// Compatibility normalization for markup produced by older product forms.
ob_start(function(string $html): string { return str_replace('value="'.csrf().'<input', 'value="'.csrf().'"><input', $html); });
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
$base=trim(parse_url(config()['base_url'],PHP_URL_PATH)??'','/'); if($base&&str_starts_with($path,$base))$path=trim(substr($path,strlen($base)),'/');
if($path==='admin'){ require __DIR__.'/admin.php'; exit; }
if($path==='logout'){session_destroy();header('Location: '.url());exit;}
if($path==='login' && $_SERVER['REQUEST_METHOD']==='POST'){ $s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([$_POST['email']??'']);$u=$s->fetch(PDO::FETCH_ASSOC);if($u&&password_verify($_POST['password']??'',$u['password'])){$_SESSION['user']=['id'=>$u['id'],'name'=>$u['name'],'role'=>$u['role']];header('Location: '.url('admin'));exit;} flash('Неверный email или пароль.');}
if($path==='login'){render_header('Вход');?><h1>Вход</h1><form method="post" class="card"><label>Email<input name="email" type="email" required></label><label>Пароль<input name="password" type="password" required></label><button>Войти</button></form><?php render_footer();exit;}
if($path==='comment' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();db()->prepare('INSERT INTO comments(content_id,name,email,body,created_at) VALUES(?,?,?,?,?)')->execute([(int)$_POST['content_id'],$_POST['name'],$_POST['email'],$_POST['body'],now()]);flash('Комментарий отправлен на модерацию.');header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
if($path==='order' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();db()->prepare('INSERT INTO orders(kind,product_id,customer_name,email,phone,message,created_at) VALUES(?,?,?,?,?,?,?)')->execute([$_POST['kind'],(int)($_POST['product_id']??0)?:null,$_POST['name'],$_POST['email'],$_POST['phone'],$_POST['message'],now()]);flash('Заявка принята. Мы свяжемся с вами.');header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
$language=lang();
// A selected page can become the homepage or the blog listing without changing its slug manually.
$homeId=(int)setting('home_page_id','0'); $blogId=(int)setting('blog_page_id','0');
if ($homeId && $path==='') { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page" AND status="published"');$q->execute([$homeId]);$homeSlug=(string)$q->fetchColumn();if($homeSlug!==''){header('Location: '.url($homeSlug),true,302);exit;} }
if ($blogId) { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page"');$q->execute([$blogId]);if($path!=='' && $path===(string)$q->fetchColumn()) $path='blog'; }
if($path==='blog'||str_starts_with($path,'category/')) { $cat=null;if(str_starts_with($path,'category/')){$s=db()->prepare('SELECT * FROM categories WHERE slug=?');$s->execute([substr($path,9)]);$cat=$s->fetch(PDO::FETCH_ASSOC);} $sql='SELECT c.*,u.name author,ca.name category FROM content c JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type="post" AND c.status="published" AND c.language=?';$args=[$language];if($cat){$sql.=' AND c.category_id=?';$args[]=$cat['id'];}$sql.=' ORDER BY c.created_at DESC';$s=db()->prepare($sql);$s->execute($args);$posts=$s->fetchAll(PDO::FETCH_ASSOC);render_header($cat?$cat['name']:'Блог');?><h1><?=e($cat['name']??'Блог')?></h1><div class="grid"><?php foreach($posts as $p):?><article class="card"><?php if($p['image']):?><img class="cover" src="<?=e($p['image'])?>" alt=""><?php endif;?><h2><a href="<?=url('post/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e(mb_strimwidth(strip_tags($p['excerpt']?:$p['body']),0,(int)setting('blog_excerpt_length','180'),'…'))?></p><small><?=e($p['category']??'')?> · <?=e($p['created_at'])?></small></article><?php endforeach;?></div><?php render_footer();exit; }
if($path==='shop'){$s=db()->prepare('SELECT * FROM content WHERE type="product" AND status="published" AND language=? ORDER BY created_at DESC');$s->execute([$language]);$items=$s->fetchAll(PDO::FETCH_ASSOC);render_header('Магазин');?><h1>Магазин</h1><div class="grid"><?php foreach($items as $p):?><article class="card"><?php if($p['image']):?><img class="cover" src="<?=e($p['image'])?>"><?php endif;?><h2><a href="<?=url('product/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e($p['excerpt'])?></p></article><?php endforeach;?></div><?php render_footer();exit;}
$parts=explode('/',$path,2);$type=match($parts[0]??''){ 'post'=>'post','product'=>'product',default=>'page'};$slug=$type==='page'?($path?:'home'):($parts[1]??'');$s=db()->prepare('SELECT c.*,u.name author,ca.name category FROM content c JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type=? AND c.slug=? AND c.language=? AND c.status="published"');$s->execute([$type,$slug,$language]);$item=$s->fetch(PDO::FETCH_ASSOC);if(!$item){http_response_code(404);render_header('Не найдено');echo '<h1>Страница не найдена</h1>';render_footer();exit;}
render_header($item['seo_title']?:$item['title']);?><article class="article <?='template-'.e($item['template'])?>"><?php if($item['image']):?><img class="hero" src="<?=e($item['image'])?>" alt=""><?php endif;?><h1><?=e($item['title'])?></h1><?php if($type==='post'):?><p class="meta"><?=e($item['author'])?> · <?=e($item['created_at'])?> <?php if($item['category']):?>· <?=e($item['category'])?><?php endif;?></p><?php endif;?><div class="content"><?=$item['body']?></div><?php if($item['review_enabled']):?><aside class="review"><b>Мнение автора</b><p><?=nl2br(e($item['review_text']))?></p></aside><?php endif;?><?php if($type==='product'):?><h2>Оформить заказ</h2><form method="post" action="<?=url('order')?>" class="card order"><input type="hidden" name="csrf" value="<?=csrf()?><input type="hidden" name="kind" value="shop"><input type="hidden" name="product_id" value="<?=$item['id']?>"><input name="name" placeholder="Ваше имя" required><input name="email" type="email" placeholder="Email" required><input name="phone" placeholder="Телефон"><textarea name="message" placeholder="Комментарий к заказу"></textarea><button>Заказать</button></form><?php endif;?><?php if($item['comments_enabled']):$q=db()->prepare('SELECT * FROM comments WHERE content_id=? AND status="approved" ORDER BY created_at');$q->execute([$item['id']]);?><section class="comments"><h2>Комментарии</h2><?php foreach($q as $c):?><div class="comment"><b><?=e($c['name'])?></b><p><?=nl2br(e($c['body']))?></p></div><?php endforeach;?><form method="post" action="<?=url('comment')?>" class="card"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="content_id" value="<?=$item['id']?>"><input name="name" placeholder="Имя" required><input name="email" type="email" placeholder="Email" required><textarea name="body" placeholder="Комментарий" required></textarea><button>Отправить</button></form></section><?php endif;?></article><?php render_footer();
