<?php
declare(strict_types=1);
if (session_status() !== PHP_ACTIVE_SESSION) {
    session_set_cookie_params(['httponly'=>true,'samesite'=>'Lax']);
    session_name('siteforge_session');
    @session_start();
}

function config(): array { static $c; if (!$c) $c = require __DIR__.'/../config.php'; return $c; }
function db(): PDO { static $p; if (!$p) { $c=config(); $p=new PDO("mysql:host={$c['db_host']};dbname={$c['db_name']};charset=utf8mb4",$c['db_user'],$c['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); } return $p; }
function e(?string $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function now(): string { return date('Y-m-d H:i:s'); }
$GLOBALS['sf_settings_cache']=[];
function setting(string $key, ?string $default=''): string { if (!array_key_exists($key,$GLOBALS['sf_settings_cache'])) { try { $s=db()->prepare('SELECT value FROM settings WHERE `key`=?');$s->execute([$key]);$GLOBALS['sf_settings_cache'][$key]=$s->fetchColumn(); } catch(Throwable $ex){ $GLOBALS['sf_settings_cache'][$key]=false; } } return $GLOBALS['sf_settings_cache'][$key]===false?$default:(string)$GLOBALS['sf_settings_cache'][$key]; }
function save_setting(string $key,string $value): void { db()->prepare('INSERT INTO settings (`key`,`value`) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)')->execute([$key,$value]); unset($GLOBALS['sf_settings_cache'][$key]); }
function url(string $path=''): string { $b=rtrim(config()['base_url'] ?? '','/'); return $b.'/'.ltrim($path,'/'); }
function logged_in(): bool { return isset($_SESSION['user']); }
function user(): ?array { return $_SESSION['user'] ?? null; }
function is_admin(): bool { return (user()['role'] ?? '')==='admin'; }
function can_edit(): bool { return in_array(user()['role'] ?? '', ['admin','editor'],true); }
function require_login(bool $admin=false): void { if (!logged_in() || ($admin&&!is_admin())) { header('Location: '.url('login')); exit; } }
function csrf(): string { if(empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(24)); return $_SESSION['csrf']; }
function verify_csrf(): void { if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')) { http_response_code(419); die('Неверный защитный токен. Обновите страницу и попробуйте снова.'); } }
function slugify(string $s): string { $s=trim($s); $t=@iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$s); $s=($t!==false&&$t!=='')?$t:$s; $s=strtolower(preg_replace('~[^a-z0-9]+~i','-',$s)); return trim($s,'-') ?: 'item'; }
function safe_url(?string $u, bool $allow_js=false): string { $u=trim((string)$u); if($u==='')return ''; $low=mb_strtolower(preg_replace('~\s+~','',$u)); foreach(['javascript:','vbscript:','data:'] as $bad){ if(str_starts_with($low,$bad)) return ''; } if(!$allow_js&&str_starts_with($low,'file:')) return ''; return $u; }
function lang(): string { if(preg_match('~^[a-z]{2}(-[A-Z]{2})?$~',$_GET['lang']??'')){ $_SESSION['lang']=$_GET['lang']; } return preg_match('~^[a-z]{2}(-[A-Z]{2})?$~',$_SESSION['lang']??'')?$_SESSION['lang']:setting('default_language','ru'); }
function languages(): array { $j=json_decode(setting('languages','{"ru":"Русский","en":"English"}'),true) ?: ['ru'=>'Русский']; return is_array($j)?$j:['ru'=>'Русский']; }
function flash(string $m=''): ?string { if($m){$_SESSION['flash']=$m;return null;} $x=$_SESSION['flash']??null;unset($_SESSION['flash']);return $x; }
function audit(string $action): void { try { db()->prepare('INSERT INTO audit_log(user_id,action,ip,created_at) VALUES(?,?,?,?)')->execute([(int)(user()['id']??0),$action,$_SERVER['REMOTE_ADDR']??'',now()]); } catch(Throwable $ex){} }
function sf_migrate(): void { static $done; if($done)return; $done=true; try { db()->exec('CREATE TABLE IF NOT EXISTS button_slots (id int unsigned AUTO_INCREMENT PRIMARY KEY, slot varchar(60) NOT NULL, button_id int unsigned NOT NULL, label varchar(100) NOT NULL, sort_order int NOT NULL DEFAULT 0, KEY slot(slot)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'); $col=db()->query("SHOW COLUMNS FROM site_buttons LIKE 'placement'")->fetch(); if($col){ db()->prepare('INSERT INTO button_slots(slot,button_id,label,sort_order) SELECT placement,id,label,0 FROM site_buttons WHERE placement<>""')->execute(); db()->exec('ALTER TABLE site_buttons DROP COLUMN placement'); } } catch(Throwable $ex){} }
function register_button_slot(string $slot,string $title): void { $GLOBALS['sf_slots'][$slot]=$title; }
function button_slots(): array { $s=['header'=>'Шапка сайта','footer'=>'Подвал сайта']; foreach($GLOBALS['sf_slots']??[] as $k=>$v)$s[$k]=$v; return $s; }
function render_buttons(string $slot): void { $q=db()->prepare('SELECT b.url,s.label FROM button_slots s JOIN site_buttons b ON b.id=s.button_id WHERE s.slot=? ORDER BY s.sort_order,s.id');$q->execute([$slot]);foreach($q as $b)echo '<a class="button" href="'.e(safe_url($b['url'])).'">'.e($b['label']).'</a>'; }
function do_action(string $hook,array $args=[]): void { foreach($GLOBALS['sf_hooks'][$hook]??[] as $cb){ try{ call_user_func_array($cb,$args); }catch(Throwable $ex){} } }
function add_action(string $hook,callable $cb): void { $GLOBALS['sf_hooks'][$hook][]=$cb; }
function apply_filters(string $hook,$value): mixed { foreach($GLOBALS['sf_hooks'][$hook]??[] as $cb){ try{ $r=call_user_func($cb,$value); if($r!==null)$value=$r; }catch(Throwable $ex){} } return $value; }
function theme_dir(): string { $t=preg_replace('~[^a-z0-9_-]~i','',setting('theme','default')) ?: 'default'; return __DIR__.'/../themes/'.$t; }
function render_header(string $title=''): void { sf_migrate(); do_action('get_header'); $site=apply_filters('site_name',setting('site_name','Мой сайт')); $logo=safe_url(setting('logo','')); ?><!doctype html><html lang="<?=e(lang())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title?:$site)?></title><link rel="stylesheet" href="<?=url('assets/style.css')?>"><link rel="stylesheet" href="<?=url('themes/'.basename(theme_dir()).'/style.css')?>"><?php do_action('wp_head');?></head><body><header class="site-header"><a class="brand" href="<?=url()?>"><?php if($logo):?><img src="<?=e($logo)?>" alt=""><?php endif;?><?=e($site)?></a><?php render_menu('header');?><div class="lang"><?php foreach(languages() as $code=>$name):?><a href="?lang=<?=$code?>"><?=e(strtoupper($code))?></a><?php endforeach;?></div><?php render_buttons('header');?></header><main class="container"><?php }
function render_footer(): void { do_action('get_footer'); ?></main><footer class="site-footer"><?php render_menu('footer'); render_buttons('footer');?> <small><?=e(setting('footer_text','© '.date('Y').' '.setting('site_name')))?></small></footer><?php do_action('wp_footer');?></body></html><?php }
function render_menu(string $location): void { $q=db()->prepare('SELECT id FROM menus WHERE location=? LIMIT 1');$q->execute([$location]);$menu=(int)$q->fetchColumn();if(!$menu)return;$s=db()->prepare('SELECT * FROM menu_items WHERE menu_id=? ORDER BY sort_order,id');$s->execute([$menu]);$items=$s->fetchAll(PDO::FETCH_ASSOC);$tree=[];foreach($items as $i)$tree[$i['parent_id']??0][]=$i; $out=function($parent=0)use(&$out,$tree){if(empty($tree[$parent]))return;echo '<ul>';foreach($tree[$parent] as $x){$tg=(int)($x['target']??0)?' target="_blank" rel="noopener"':'';echo '<li><a href="'.e(safe_url($x['url'])?:'#').'"'.$tg.'>'.e($x['label']).'</a>'; $out((int)$x['id']);echo '</li>';}echo '</ul>';};echo '<nav>';$out();echo '</nav>'; }
function load_plugins(): void { sf_migrate(); do_action('mu_plugins'); $active=json_decode(setting('active_plugins','[]'),true); $active=is_array($active)?$active:[]; foreach(glob(__DIR__.'/../plugins/*.php')?:[] as $f){ if(in_array(basename($f),$active,true)){ try { include_once $f; } catch(Throwable $ex){} } } do_action('plugins_loaded'); }
/* --- Extensions: plugin & theme installer (upload .zip or folder in packages/) --- */
function sf_package_types(): array { return ['plugin'=>['packages/plugins','plugins','sf_plugin'], 'theme'=>['packages/themes','themes','sf_theme']]; }
function sf_package_readme(string $dir): array { $out=[]; foreach(scandir($dir)?:[] as $f){ if(!preg_match('~^readme\\.(txt|json)$~i',$f))continue; $t=file_get_contents($dir.'/'.$f); if(str_ends_with(strtolower($f),'.json')){ $j=json_decode($t,true); if(is_array($j))$out=$j; } else { foreach(explode("\\n",$t) as $ln){ if(preg_match('~^\\s*([A-Za-z][A-Za-z -]{1,20}):\\s*(.+)$~',trim($ln),$m))$out[strtolower(trim($m[1]))]=trim($m[2]); } } break; } return $out; }
function sf_package_list(string $type): array { [$pkg_dir,$dest_dir,$tag]=sf_package_types()[$type]; $res=[]; $base=__DIR__.'/../'.$dest_dir; foreach(glob($base.'/*',$type==='theme'?GLOB_ONLYDIR:0)?:[] as $p){ $name=basename($p); if($name==='default'&&$type==='theme'){$readme=['name'=>'Default','title'=>'Стандартная тема'];} else $readme=sf_package_readme($type==='theme'?$p:$p); if($type==='plugin'){ if(!preg_match('~<\\?php[^>]*\\b'.$tag.'\\b~i',(string)@file_get_contents($p))) continue; } $res[$name]=$readme; } ksort($res); return $res; }
function sf_available_packages(): array { [$pkg_dir,,$tag]=['','','']; $res=[]; foreach(sf_package_types() as $type=>[$pd,$dd]) { foreach(glob(__DIR__.'/../'.$pd.'/*')?:[] as $p){ $name=preg_replace('~\\.(zip|tar\\.gz)$~i','',basename($p)); $res[]=['type'=>$type,'name'=>$name,'path'=>$p,'local'=>is_dir($p)?sf_package_readme($p):[], 'installed'=>file_exists(__DIR__.'/../'.$dd.'/'.$name)]; } } return $res; }
function sf_safe_extract(string $archive,string $dest): bool { if(!class_exists('ZipArchive'))return false; $z=new ZipArchive(); if($z->open($archive)!==true)return false; $ok=true; for($i=0;$i<$z->numFiles;$i++){ $n=$z->getNameIndex($i); $rel=trim(str_replace('\\','/',$n),'/'); if($rel===''||str_contains($rel,'..')||preg_match('~^(/|[a-z]:)~i',$rel)){$ok=false;break;} $full=rtrim($dest,'/').'/'.$rel; if(str_ends_with($n,'/')){ if(!is_dir($full)&&!mkdir($full,0755,true)&&!is_dir($full)){$ok=false;break;} continue; } $par=dirname($full); if(!is_dir($par)&&!mkdir($par,0755,true)){$ok=false;break;} $in=$z->getStream($n); if(!$in){$ok=false;break;} $out=fopen($full,'wb'); stream_copy_to_stream($in,$out); fclose($in); fclose($out); } $z->close(); return $ok; }
function sf_install_package(string $type,string $source): array { if(!isset(sf_package_types()[$type]))return[false,'Неизвестный тип расширения.']; [$pd,$dd,$tag]=sf_package_types()[$type]; $base=__DIR__.'/../'; $tmp=null; if(is_dir($source)){$src_dir=$source;} elseif(preg_match('~\\.zip$~i',$source)){ if(!class_exists('ZipArchive'))return[false,'На сервере нет расширения ZipArchive — загрузите распакованную папку в '.$pd.'/']; $tmp=$base.$pd.'/.tmp-'.bin2hex(random_bytes(4)); mkdir($tmp,0755,true); if(!sf_safe_extract($source,$tmp)){rmdir($tmp);return[false,'Не удалось распаковать архив.'];} $kids=array_values(array_filter(glob($tmp.'/*')?:[],'is_dir')); if(count($kids)!==1){array_map('unlink',glob($tmp.'/*'));rmdir($tmp);return[false,'В архиве должна быть одна папка с расширением.'];} $src_dir=$kids[0]; } else return[false,'Пакет не найден.'];
 $name=basename($src_dir); if(!preg_match('~^[a-z0-9_-]+$~i',$name))return[false,'Некорректное имя пакета.'];
 if($type==='plugin'){ $entry=$src_dir.'/'.$name.'.php'; if(!is_file($entry))return[false,'В пакете нет главного файла '.$name.'.php']; if(!preg_match('~\\b'.$tag.'\\b~i',(string)file_get_contents($entry)))return[false,'В главном файле плагина нет заголовка «'.$tag.': ...» — пакет не распознан как плагин.']; $ext='/\\.php$/i'; } else { if(!is_file($src_dir.'/style.css'))return[false,'В теме нет файла style.css']; if(!preg_match('~\\b'.$tag.'\\b~i',(string)file_get_contents($src_dir.'/style.css')))return[false,'В style.css темы нет заголовка «'.$tag.': ...».']; $ext='/(\\.php|\\.css|\\.js)$/i'; }
 $dest=$base.$dd.'/'.$name; if(is_dir($dest))return[false,'«'.$name.'» уже установлено.']; @mkdir($base.$dd,0755,true); $move=function($from,$to)use(&$move,$ext){ if(is_dir($from)){ @mkdir($to,0755,true); foreach(scandir($from)?:[] as $f){ if($f==='.'||$f==='..'||$f==='.git')continue; $move($from.'/'.$f,$to.'/'.$f);} return; } if(!preg_match($ext,$from))return; copy($from,$to); }; $move($src_dir,$dest); if($tmp){ $rm=function($d){foreach(scandir($d)?:[] as $f){if($f==='.'||$f==='..')continue; $p=$d.'/'.$f; is_dir($p)?$rm($p):@unlink($p);} @rmdir($d);}; $rm($tmp); }
 return [true,$name]; }
function sf_active_plugins(): array { $a=json_decode(setting('active_plugins','[]'),true); return is_array($a)?$a:[]; }
function sf_set_active_plugins(array $list): void { save_setting('active_plugins',json_encode(array_values(array_unique(array_filter($list,function($x){return preg_match('~^[a-z0-9_.-]+\\.php$~i',$x);}))))); }
load_plugins();
