<?php
if (!file_exists(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require __DIR__.'/app/core.php';
$path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
$base=trim(parse_url(config()['base_url'],PHP_URL_PATH)??'','/'); if($base&&str_starts_with($path,$base))$path=trim(substr($path,strlen($base)),'/');
if($path==='sitemap.xml'){ header('Content-Type: application/xml; charset=utf-8'); echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'; $urls=[]; try { foreach(db()->query("SELECT type,slug,updated_at FROM content WHERE status='published'")->fetchAll(PDO::FETCH_ASSOC) as $sm){ $type=$sm['type']; $u=site_base().url($type==='page'?($sm['slug']==='home'?'':$sm['slug']):($type.'/'.$sm['slug'])); $urls[$u]=date('Y-m-d',strtotime((string)$sm['updated_at'])); } } catch(Throwable $ex){} $urls[site_base().url('')]=date('Y-m-d'); $urls[site_base().url('blog')]=date('Y-m-d'); $urls[site_base().url('shop')]=date('Y-m-d'); foreach($urls as $u=>$d)echo '<url><loc>'.htmlspecialchars($u,ENT_XML1).'</loc><lastmod>'.$d.'</lastmod></url>'; echo '</urlset>'; exit; }
if($path==='robots.txt'){ header('Content-Type: text/plain; charset=utf-8'); echo "User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /login\nDisallow: /sessions\nSitemap: ".site_base().url('sitemap.xml')."\n"; exit; }
if($path==='admin'){ require __DIR__.'/admin.php'; exit; }
$safe_return=url();if(!empty($_SERVER['HTTP_REFERER'])){$ref=parse_url($_SERVER['HTTP_REFERER']);$host=explode(':',$_SERVER['HTTP_HOST']??'')[0];if(($ref['host']??'')===$host)$safe_return=$_SERVER['HTTP_REFERER'];}
if($path==='logout'){if(logged_in()){audit('logout');} $_SESSION=[];session_destroy();header('Location: '.url());exit;}
if($path==='login' && $_SERVER['REQUEST_METHOD']==='POST'){ $s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([$_POST['email']??'']);$u=$s->fetch(PDO::FETCH_ASSOC);if($u&&password_verify($_POST['password']??'',$u['password'])){session_regenerate_id(true);$_SESSION['user']=['id'=>$u['id'],'name'=>$u['name'],'role'=>$u['role']];audit('login');if(session_status()===PHP_SESSION_ACTIVE){header('Location: '.url('admin'));exit;} flash('Сервер не может сохранить сессию (нужен доступ на запись для папки sessions). Откройте /index.php?retry=login&diag=1.');} else flash('Неверный email или пароль.');}
if($path==='login'){render_header('Вход');?><h1>Вход</h1><form method="post" class="card"><label>Email<input name="email" type="email" required></label><label>Пароль<input name="password" type="password" required></label><button>Войти</button></form><p class="hint">Не получается войти? <a href="<?=e(url('login'))?>&diag=1">Диагностика сессий</a><?php if(!empty($_GET['diag'])){$d=sf_session_diag();echo '<p class="notice">Диагностика сессий: статус='.e((string)$d['status']).', путь сохранения='.e($d['save_path']?:'(по умолчанию)').', запись в путь='.e((string)$d['writable']).', куки от браузера='.e($d['cookies_received']).'. Если «куки от браузера» = NONE — браузер не отправляет cookie (проверьте блокировщики/режим инкогнито).</p>'; render_footer();exit;} $flash_msg=flash(); if($flash_msg!==null)echo '<p class="error">'.e($flash_msg).'</p>'; if(logged_in()===false&&!empty($_GET['retry'])){echo '<p class="error">Сессия не сохранилась: сервер не смог записать данные сессии. Откройте /index.php?retry=login&diag=1 для подробностей.</p>';} render_footer();exit;}
// Self-heal: if a browser reports it cannot log in, open the login page with ?retry=login to re-check session storage.
if($path==='' && !empty($_GET['retry']) && $_GET['retry']==='login' && logged_in()) { header('Location: '.url('admin')); exit; }
if($path==='comment' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();db()->prepare('INSERT INTO comments(content_id,name,email,body,created_at) VALUES(?,?,?,?,?)')->execute([(int)$_POST['content_id'],mb_substr((string)($_POST['name']??''),0,120),mb_substr((string)($_POST['email']??''),0,190),mb_substr((string)($_POST['body']??''),0,5000),now()]);flash('Комментарий отправлен на модерацию.');header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
if($path==='order' && $_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();db()->prepare('INSERT INTO orders(kind,product_id,customer_name,email,phone,message,created_at) VALUES(?,?,?,?,?,?,?)')->execute([in_array($_POST['kind']??'',['service','shop'],true)?$_POST['kind']:'service',(int)($_POST['product_id']??0)?:null,mb_substr((string)($_POST['name']??''),0,120),mb_substr((string)($_POST['email']??''),0,190),mb_substr((string)($_POST['phone']??''),0,50),mb_substr((string)($_POST['message']??''),0,5000),now()]);flash('Заявка принята. Мы свяжемся с вами.');header('Location: '.($_SERVER['HTTP_REFERER']??url()));exit;}
$language=lang();
// A selected page can become the homepage or the blog listing without changing its slug manually.
$homeId=(int)setting('home_page_id','0'); $blogId=(int)setting('blog_page_id','0');
if ($homeId && $path==='') { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page" AND status="published"');$q->execute([$homeId]);$homeSlug=(string)$q->fetchColumn();if($homeSlug!==''){header('Location: '.url($homeSlug),true,302);exit;} }
if ($blogId) { $q=db()->prepare('SELECT slug FROM content WHERE id=? AND type="page"');$q->execute([$blogId]);if($path!=='' && $path===(string)$q->fetchColumn()) $path='blog'; }
if($path==='blog'||str_starts_with($path,'category/')) { $cat=null;if(str_starts_with($path,'category/')){$s=db()->prepare('SELECT * FROM categories WHERE slug=?');$s->execute([substr($path,9)]);$cat=$s->fetch(PDO::FETCH_ASSOC);} $sql='SELECT c.*,u.name author,ca.name category FROM content c LEFT JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type="post" AND c.status="published" AND c.language=?';$args=[$language];if($cat){$sql.=' AND c.category_id=?';$args[]=$cat['id'];}$sql.=' ORDER BY c.created_at DESC';$s=db()->prepare($sql);$s->execute($args);$posts=$s->fetchAll(PDO::FETCH_ASSOC);render_header($cat?$cat['name']:'Блог', $cat?(string)$cat['description']:trim(setting('blog_description')));?><h1><?=e($cat['name']??'Блог')?></h1><div class="grid"><?php foreach($posts as $p):?><article class="card"><?php if($p['image']):?><img class="cover" loading="lazy" decoding="async" src="<?=e($p['image'])?>" alt="<?=e($p['title'])?>"><?php endif;?><h2><a href="<?=url('post/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e(mb_strimwidth(strip_tags($p['excerpt']?:$p['body']),0,(int)setting('blog_excerpt_length','180'),'…'))?></p><small><?=e($p['category']??'')?> · <?=e($p['created_at'])?></small></article><?php endforeach;?></div><?php render_footer();exit; }
if($path==='shop'){$s=db()->prepare('SELECT * FROM content WHERE type="product" AND status="published" AND language=? ORDER BY created_at DESC');$s->execute([$language]);$items=$s->fetchAll(PDO::FETCH_ASSOC);render_header('Услуги и товары', trim(setting('shop_description')));?><h1><?=e(setting('shop_title','Услуги и товары'))?></h1><div class="grid"><?php foreach($items as $p):?><article class="card"><?php if($p['image']):?><img class="cover" loading="lazy" decoding="async" src="<?=e($p['image'])?>" alt="<?=e($p['title'])?>"><?php endif;?><h2><a href="<?=url('product/'.$p['slug'])?>"><?=e($p['title'])?></a></h2><p><?=e($p['excerpt'])?></p></article><?php endforeach;?></div><?php render_footer();exit;}
$parts=explode('/',$path,2);$type=match($parts[0]??''){ 'post'=>'post','product'=>'product',default=>'page'};$slug=$type==='page'?($path?:'home'):($parts[1]??'');$s=db()->prepare('SELECT c.*,u.name author,ca.name category FROM content c LEFT JOIN users u ON u.id=c.author_id LEFT JOIN categories ca ON ca.id=c.category_id WHERE c.type=? AND c.slug=? AND c.language=? AND c.status="published"');$s->execute([$type,$slug,$language]);$item=$s->fetch(PDO::FETCH_ASSOC);if(!$item){http_response_code(404);render_header('Не найдено');echo '<h1>Страница не найдена</h1>';render_footer();exit;}
$itemDesc=(string)($item['seo_description']?:mb_strimwidth(strip_tags((string)($item['excerpt']?:$item['body'])),0,300,'…'));
render_header($item['seo_title']?:$item['title'],$itemDesc);
echo sf_page_schema($item);?><article class="article <?='template-'.e($item['template'])?>"><?php if($item['image']):?><img class="hero" src="<?=e($item['image'])?>" alt="<?=e($item['title'])?>"><?php endif;?><h1><?=e($item['title'])?></h1><?php render_buttons('content:'.$item['id']);?><?php if($type==='post'):?><p class="meta"><?=e($item['author'])?> · <?=e($item['created_at'])?> <?php if($item['category']):?>· <?=e($item['category'])?><?php endif;?></p><?php endif;?><div class="content"><?=sf_render_shortcodes(apply_filters('the_content',$item['body']))?></div><?php if($item['review_enabled']):?><aside class="review"><b>Мнение автора</b><p><?=nl2br(e($item['review_text']))?></p></aside><?php endif;?><?php if($type==='product'):?><h2 id="order">Оставить заявку на услугу</h2><?php $sf_tel=preg_replace('~[^\d+]~','',trim(setting('company_phone'))); ?><?php if($sf_tel!==''):?><p class="hint">Или позвоните: <a href="tel:<?=e($sf_tel)?>"><?=e(setting('company_phone'))?></a><?php if(trim(setting('company_hours'))!==''):?> (<?=e(setting('company_hours'))?>)<?php endif;?></p><?php endif;?><form method="post" action="<?=url('order')?>" class="card order"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="kind" value="shop"><input type="hidden" name="product_id" value="<?=$item['id']?>"><input name="name" placeholder="Ваше имя" required><input name="email" type="email" placeholder="Email" required><input name="phone" placeholder="Телефон" inputmode="tel"><textarea name="message" placeholder="Комментарий к заявке"></textarea><button>Отправить заявку</button></form><?php endif;?><?php if($item['comments_enabled']):$q=db()->prepare('SELECT * FROM comments WHERE content_id=? AND status="approved" ORDER BY created_at');$q->execute([$item['id']]);?><section class="comments"><h2>Комментарии</h2><?php foreach($q as $c):?><div class="comment"><b><?=e($c['name'])?></b><p><?=nl2br(e($c['body']))?></p></div><?php endforeach;?><form method="post" action="<?=url('comment')?>" class="card"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="content_id" value="<?=$item['id']?>"><input name="name" placeholder="Имя" required><input name="email" type="email" placeholder="Email" required><textarea name="body" placeholder="Комментарий" required></textarea><button>Отправить</button></form></section><?php endif;?></article><?php render_footer();
